### ISSUE TITLE
problem with android L and above 

### ISSUE THREAD

**Issue by sumitk91** [timmywil/jquery.panzoom#319] opened 2017-02-14 07:19 UTC
### Subject of the issue
I am trying to use panzoom plugin in my cordova application. It is working fine in android K devices but when I am trying to run it in android L and above devices pinch zoom is not working. Panning is working properly, Please help me out.

### Your environment
* I am using latest version of panzoom
* Version of jquery is 3.1.1
* Android M cordova application

### Steps to reproduce
Here is the link to apk file
https://drive.google.com/file/d/0B0kMQ1a4hnbwRFpXTS1RMmtLY3c/view?usp=sharing

### Expected behaviour
I want to zoom and pan a div element not image.

### Actual behaviour
Pinch zooming is not working.

**Comment by Risingson** [comment] 2017-03-13 10:31
see #303

**Comment by jcnventura** [comment] 2017-06-25 00:17
Duplicate of #303.

**Closed by jcnventura** 2017-06-25 00:17 UTC
