### ISSUE TITLE
panOnlyWhenZoomed doesn't allow to zoom out on Android Chrome 56

### ISSUE THREAD

**Issue by adamromero** [timmywil/jquery.panzoom#326] opened 2017-03-17 21:20 UTC
### Subject of the issue
When setting panOnlyWhenZoomed: true, after pinch zooming, I'm unable to zoom out, instead the image jumps around. This specifically appears to happen when you pinch zoom, lift finger tips from the screen, and then, try to zoom out. Zooming in and out seems to work as long as you continue to touch the screen. Works perfectly on Firefox, haven't tried other browsers or devices.

### Your environment
* jquery.panzoom 3.2.2
* jquery 2.2.4 & 3.1.1
* Chrome 56 on Android

### Steps to reproduce
Open this on chrome 56 on mobile device.
https://adamromero.github.io/issue/

### Expected behaviour
Should be able to zoom out when only allowing panning on zoomed image

### Actual behaviour
Can't zoom out on zoomed image using panOnlyWhenZoomed.

**Comment by inuyaksa** [comment] 2017-05-09 06:49
Some as #330 (fixed with my pull request)

**Comment by jcnventura** [comment] 2017-06-24 21:20
Duplicate of #303

**Closed by jcnventura** 2017-06-24 21:20 UTC
