### ISSUE TITLE
Blurred zoom when using touch

### ISSUE THREAD

**Issue by vic3685** [timmywil/jquery.panzoom#181] opened 2015-04-20 21:07 UTC
When I use zoom in/out buttons, the SVG zooms nicely and lines remain crisp. If I use pinch actions to zoom, the SVG is very blurry and remains that way even if I zoom out or start using the buttons. 

I'm using an XML SVG for a map. Here's a code sample: http://6vlab.com.ar/map/

I am testing this on Android 4.4, both on the native browser and Chrome.

**Comment by henkkelder** [comment] 2015-04-22 22:52
I am seeing the same.. but not quite. Android 5.0 in Phonegap (= webview)
Whenever my SVG fills the entire viewport it does not occur.
But when only part of the screen it becomes blur. Only on android, not on IOS, not in Chrome.

Applying these css statements to my svg container helps only for the fullscreen and for chrome on my browser.
  -webkit-backface-visibility: initial!important;
    backface-visibility: initial!important;
    transform-origin: 50% 50%;

**Comment by henkkelder** [comment] 2015-04-22 23:16
Just found something that solves my problem:

I added the following to the onEnd callback:
...
onEnd: function (e, instance, matrix, changed) {
       var sel = _plattegrond[0];
       sel.style.display = 'none';
       sel.offsetHeight; // no need to store this anywhere, the reference is enough
       sel.style.display = '';
       }

During the pinch the image becomes blur, but just when I lift my fingers the image becomes sharp again.

**Comment by timmywil** [comment] 2016-07-15 19:32
Duplicate of #84

**Closed by timmywil** 2016-07-15 19:32 UTC
